--- #YAML:1.0
name:                Tk-XMLViewer
version:             0.19
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Tk:                            800.013
    XML::Parser:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
