--- #YAML:1.0
name:               Tk-XMLViewer
version:            0.21
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Tk:           800.013
    XML::Parser:  0
resources:
    repository:  git://github.com/eserte/tk-xmlviewer.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
